// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Payments.Api.Persistence;

#nullable disable

namespace Payments.Api.Persistence.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    [Migration("20250106150101_Added_Common_Stripe_Enums")]
    partial class Added_Common_Stripe_Enums
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("payments")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payments", "stripe_mode", new[] { "live", "test" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payments", "stripe_status", new[] { "active", "inactive" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
